@startuml urbanstore
' ----------
' UI
' ----------
' ----------
' ログイン画面
' ----------
class LoginScreen
' ----------
' ユーザー登録画面
' ----------
class UserRegistrationScreen
' ----------
' ログアウト画面
' ----------
class UserRegistrationScreen
' ----------
' ホーム画面
' ----------
class HomeScreen
' ----------
' 商品詳細表示画面
' ----------
class ItemDetailScreen
' ----------
' 商品検索機能画面
' ----------
class ProductSearchFunctionScreen
' ----------
' カート管理画面
' ----------
class CartManagementScreen
' ----------
' 購入手続き画面
' ----------
class PurchaseProcedureScreen
' ----------
' カート管理画面
' ----------
class CartManagementScreen
' ----------
' 購入手続き画面
' ----------
class PurchaseProcedureScreen
' ----------
' 注文履歴表示画面
' ----------
class OrderHistoryDisplayScreen
' ----------
' 注文詳細表示画面
' ----------
class OrderDetailDisplayScreen

@enduml