// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2azH3lblsWN4ZeKSmESDivU6U22W9kjc',
    appId: '1:756260024222:web:0458ed1d2966940b74708f',
    messagingSenderId: '756260024222',
    projectId: 'urbanstore-86068',
    authDomain: 'urbanstore-86068.firebaseapp.com',
    storageBucket: 'urbanstore-86068.appspot.com',
    measurementId: 'G-6FGH4EWDCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5hgmBX3XptEDhE4bXpnQDiI3xc-FqBPc',
    appId: '1:756260024222:android:040934a4d2f96bfb74708f',
    messagingSenderId: '756260024222',
    projectId: 'urbanstore-86068',
    storageBucket: 'urbanstore-86068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSPO5EZI4DRjsOyaypnGqVw_55r_Aftuo',
    appId: '1:756260024222:ios:5243767f4519b2f574708f',
    messagingSenderId: '756260024222',
    projectId: 'urbanstore-86068',
    storageBucket: 'urbanstore-86068.appspot.com',
    iosBundleId: 'com.example.urbanstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSPO5EZI4DRjsOyaypnGqVw_55r_Aftuo',
    appId: '1:756260024222:ios:5243767f4519b2f574708f',
    messagingSenderId: '756260024222',
    projectId: 'urbanstore-86068',
    storageBucket: 'urbanstore-86068.appspot.com',
    iosBundleId: 'com.example.urbanstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2azH3lblsWN4ZeKSmESDivU6U22W9kjc',
    appId: '1:756260024222:web:02caeba503c9c0f874708f',
    messagingSenderId: '756260024222',
    projectId: 'urbanstore-86068',
    authDomain: 'urbanstore-86068.firebaseapp.com',
    storageBucket: 'urbanstore-86068.appspot.com',
    measurementId: 'G-B508TN9GM2',
  );
}
