import 'package:urbanstore/model/product.dart';

final List<Product> productListTest = [
  Product(
      id: '0001',
      name: 'Product 1',
      description: 'Description 1',
      price: 10.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 100),
  Product(
      id: '0002',
      name: 'Product 2',
      description: 'Description 2',
      price: 20.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 200),
  Product(
      id: '0003',
      name: 'Product 3',
      description: 'Description 3',
      price: 30.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 300),
  Product(
      id: '0004',
      name: 'Product 4',
      description: 'Description 4',
      price: 40.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 400),
  Product(
      id: '0005',
      name: 'Product 5',
      description: 'Description 5',
      price: 50.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 500),
  Product(
      id: '0006',
      name: 'Product 6',
      description: 'Description 6',
      price: 60.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 600),
  Product(
      id: '0007',
      name: 'Product 7',
      description: 'Description 7',
      price: 70.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 700),
  Product(
      id: '0008',
      name: 'Product 8',
      description: 'Description 8',
      price: 80.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 800),
  Product(
      id: '0009',
      name: 'Product 9',
      description: 'Description 9',
      price: 90.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 900),
  Product(
      id: '0010',
      name: 'Product 10',
      description: 'Description 10',
      price: 100.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1000),
  Product(
      id: '0011',
      name: 'Product 11',
      description: 'Description 11',
      price: 110.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1100),
  Product(
      id: '0012',
      name: 'Product 12',
      description: 'Description 12',
      price: 120.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1200),
  Product(
      id: '0013',
      name: 'Product 13',
      description: 'Description 13',
      price: 130.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1300),
  Product(
      id: '0014',
      name: 'Product 14',
      description: 'Description 14',
      price: 140.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1400),
  Product(
      id: '0015',
      name: 'Product 15',
      description: 'Description 15',
      price: 150.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1500),
  Product(
      id: '0016',
      name: 'Product 16',
      description: 'Description 16',
      price: 160.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1600),
  Product(
      id: '0017',
      name: 'Product 17',
      description: 'Description 17',
      price: 170.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1700),
  Product(
      id: '0018',
      name: 'Product 18',
      description: 'Description 18',
      price: 180.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1800),
  Product(
      id: '0019',
      name: 'Product 19',
      description: 'Description 19',
      price: 190.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 1900),
  Product(
      id: '0020',
      name: 'Product 20',
      description: 'Description 20',
      price: 200.0,
      imageUrl: 'assets/noimage.png',
      stockQuantity: 2000),
];
